name: Diagnóstico em caso de falha do Terraform

on:
  workflow_run:
    workflows: ["Terraform Workflow"]
    types:
      - completed

jobs:
  review_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Mostrar informações básicas da falha
        run: |
          echo "Workflow falhou!"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"

      - name: Baixar log da falha Terraform Apply
        uses: actions/download-artifact@v3
        with:
          name: terraform-apply-log
          path: ./logs

      - name: Mostrar informações básicas da falha
        run: |
          echo "Workflow falhou!"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"
          echo "Conteúdo do log:"
          cat ./logs/apply.log

      - name: Diagnóstico IA via Groq
        id: diagnosis
        uses: rajsinghparihar/llm-code-review@v0.0.1-groq
        with:
          apiKey: ${{ secrets.GROQ_API_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubRepository: ${{ github.repository }}
          gitCommitHash: ${{ github.event.workflow_run.head_sha }}
          repoId: "llama3-70b-8192"
          temperature: "0.2"
          maxNewTokens: "256"
          logLevel: "DEBUG"
          pullRequestDiff: ""
          githubPullRequestNumber: 0 

    
      - name: Postar comentário no PR com a análise da IA
        if: ${{ github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0] }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEW_TEXT: ${{ steps.diagnosis.outputs.review }}
        run: |
          PR_NUMBER=${{ github.event.workflow_run.pull_requests[0].number }}
          echo "Comentando no PR #$PR_NUMBER"
          echo "$REVIEW_TEXT"
          gh auth setup-git
          gh pr comment $PR_NUMBER --body "$REVIEW_TEXT"

