name: Diagnóstico em caso de falha do Terraform

on:
  workflow_run:
    workflows: ["Terraform Workflow"]
    types:
      - completed

jobs:
  review_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Mostrar informações básicas da falha
        run: |
          echo "Workflow falhou!"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"

      - name: Diagnóstico IA via Groq
        uses: rajsinghparihar/llm-code-review@v0.0.1-groq
        with:
          apiKey: ${{ secrets.GROQ_API_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubRepository: ${{ github.repository }}
          gitCommitHash: ${{ github.event.workflow_run.head_sha }}
          repoId: "llama3-70b-8192"
          temperature: "0.2"
          maxNewTokens: "256"
          logLevel: "DEBUG"
          pullRequestDiff: ""
          githubPullRequestNumber: 0 
